POST http://127.0.0.1:8080/v1/coupons
Content-Type: application/json

{
  "eventId": "",
  "couponTypeId":"",
  "couponCode": "",
  "description":"",
  "amount": "",
  "validFrom":"",
  "validTo": "",
  "totalQuantity":"",
  "remainingQuantity": ""
}